name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: suefabot/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (unit + integration)
        env:
          SECRET_KEY: test-secret
        run: |
          pytest -m "unit or integration" --maxfail=1 --disable-warnings -q

  build-docker:
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build images
        run: |
          docker build -t suefabot-backend:ci suefabot/backend
          docker build -t suefabot-bot:ci suefabot/bot
          docker build -t suefabot-webapp:ci suefabot/webapp