name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: suefabot/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --only-binary=:all: || true
          pip install pytest
      - name: Run unit tests (game logic)
        env:
          PYTHONPATH: .
        run: |
          pytest -q tests/test_game_logic.py

  backend-integration:
    runs-on: ubuntu-latest
    needs: backend-unit
    defaults:
      run:
        working-directory: suefabot/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run integration tests (with mocks)
        env:
          PYTHONPATH: .
          SECRET_KEY: test-secret
        run: |
          pytest -m integration -q

  frontend-build:
    runs-on: ubuntu-latest
    needs: backend-unit
    defaults:
      run:
        working-directory: suefabot/webapp
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Build
        env:
          REACT_APP_API_URL: http://localhost:5000
          REACT_APP_WS_URL: ws://localhost:5000
          REACT_APP_SENTRY_DSN: ''
        run: npm run build --silent

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-integration, frontend-build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build images
        run: |
          docker build -t suefabot-backend:ci suefabot/backend
          docker build -t suefabot-bot:ci suefabot/bot
          docker build -t suefabot-webapp:ci suefabot/webapp